sudo: false

language: node_js

os:
  - linux

node_js:
  - 6

cache:
  yarn: true
  directories:
    - node_modules

script:
  - node --version
  - yarn --version
  - yarn test
  - yarn test:report

after_success: "yarn test:coverage"

notifications:
  email: false